name: Compile

on:
  schedule:
    - cron: '0 0 * * *'  # egunero gauerdian

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.2.4

    - name: Execute project
      run: haxe -main Main --interp

    - name: Setup git config
      run: |
        # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"

    - name: Commit and push
      run: |
        # Stage the file, commit and push
        git add readme.md
        git commit -m "gaur lanera?"
        git push origin main
