name: Compile

on:
  schedule:
    - cron: '0 0 * * *'  # egunero gauerdian

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4

    - name: Compile project
      run: haxe -main Main --interp

    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
